# Optional sops-nix wiring: ONE age-encrypted dotenv file, held by the private
# overlay, decrypted at activation into the /run/secrets ramfs. The overlay
# opts in by setting `sopsSecretsFile`; with it null (the default) this module
# contributes nothing and the box keeps sourcing the hand-written
# ~/.config/tyc/secrets.env (nix/home/zsh.nix falls back to it either way).
#
# Why this shape (WP-BACKUP-CRYPT, ruled 2026-09-02): the plaintext secrets.env
# was the one file that kept whole-disk/agent backups of these boxes cleartext.
# With sops the repo and every backup carry ciphertext only; the single
# plaintext left at rest is the host's age identity at `sopsAgeKeyFile` — small,
# rotatable (edit .sops.yaml recipients + `sops updatekeys`), and on a guest
# with a dedicated secrets disk (tycdev scsi2, backup=false) not even that
# reaches a backup. Decryption target is a ramfs, so plaintext touches neither
# disk nor swap at runtime.
#
# The key is generated by the ENROLMENT runbook, never here: generateKey would
# mint a fresh identity the secrets file is not encrypted to and turn a missing
# key into a confusing decrypt failure one step later. A missing key fails the
# activation loudly with the keyFile path in the message instead.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.flakelab;
in
{
  config = lib.mkIf (cfg.sopsSecretsFile != null) {
    sops = {
      defaultSopsFile = cfg.sopsSecretsFile;
      age = {
        keyFile = cfg.sopsAgeKeyFile;
        generateKey = false;
        # Explicitly empty: deriving recipients from the SSH host key would put
        # the decryption identity on the root disk — exactly what the tycdev
        # secrets-disk split exists to avoid — and host keys rotate with a
        # re-image, silently orphaning the file.
        sshKeyPaths = [ ];
      };
      gnupg.sshKeyPaths = [ ];
      secrets.tyc-env = {
        format = "dotenv";
        # "" = the whole decrypted file: zsh.nix `source`s it as-is, so the
        # operator encrypts their existing secrets.env byte-for-byte and every
        # quoting decision in it survives the round trip.
        key = "";
        # 0400, owned by the login: the same exposure the 0600 home file had,
        # minus the at-rest copy.
        owner = cfg.username;
      };
    };

    # The enrolment/rotation tools on the box that uses them: `sops` to edit or
    # re-key the encrypted file in the overlay checkout, `age` for key custody
    # (`age-keygen -y` prints the recipient to enrol).
    environment.systemPackages = [
      pkgs.sops
      pkgs.age
    ];
  };
}
