# Optional sops-nix wiring: ONE age-encrypted dotenv file, held by the private
# overlay, decrypted at activation into the /run/secrets ramfs. The overlay
# opts in by setting `sopsSecretsFile`; with it null (the default) this module
# contributes nothing and the box keeps sourcing the hand-written
# ~/.config/tyc/secrets.env (nix/home/zsh.nix falls back to it either way).
#
# Why this shape (WP-BACKUP-CRYPT, ruled 2026-09-02): the plaintext secrets.env
# was the one file that kept whole-disk/agent backups of these boxes cleartext.
# With sops the repo and every backup carry ciphertext only; the single
# plaintext left at rest is the host's age identity at `sopsAgeKeyFile` — small,
# rotatable (edit .sops.yaml recipients + `sops updatekeys`), and on a guest
# with a dedicated secrets disk (tycdev scsi2, backup=false) not even that
# reaches a backup. Decryption target is a ramfs, so plaintext touches neither
# disk nor swap at runtime.
#
# The key is generated by the ENROLMENT runbook, never here: generateKey would
# mint a fresh identity the secrets file is not encrypted to and turn a missing
# key into a confusing decrypt failure one step later. A missing key fails the
# activation loudly with the keyFile path in the message instead.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.flakelab;
in
{
  config = lib.mkIf (cfg.sopsSecretsFile != null) {
    sops = {
      defaultSopsFile = cfg.sopsSecretsFile;
      # The systemd-unit variant, NOT the default activation script: the
      # activation script runs before systemd mounts anything outside the
      # initrd, so a key on its own filesystem (tycdev's scsi2 disk) would
      # decrypt fine on `nixos-rebuild switch` and then fail every BOOT with
      # `cannot read keyfile`. The unit variant orders itself after the key's
      # mount (RequiresMountsFor on age.keyFile).
      useSystemdActivation = true;
      age = {
        keyFile = cfg.sopsAgeKeyFile;
        generateKey = false;
        # Explicitly empty: deriving recipients from the SSH host key would put
        # the decryption identity on the root disk — exactly what the tycdev
        # secrets-disk split exists to avoid — and host keys rotate with a
        # re-image, silently orphaning the file.
        sshKeyPaths = [ ];
      };
      gnupg.sshKeyPaths = [ ];
      secrets.tyc-env = {
        # dotenv (like binary/ini) renders the WHOLE decrypted file — there is
        # no per-key lookup on this path. Values, quoting and comments survive
        # the round trip verbatim; blank lines do not (the dotenv store drops
        # them on re-serialisation), which no `source` consumer can notice.
        format = "dotenv";
        # 0400, owned by the login: the same exposure the 0600 home file had,
        # minus the at-rest copy. Explicit, not sops-nix's default, because
        # the shell contract depends on it.
        mode = "0400";
        owner = cfg.username;
      };
    };

    # The enrolment/rotation tools on the box that uses them: `sops` to edit or
    # re-key the encrypted file in the overlay checkout, `age` for key custody
    # (`age-keygen -y` prints the recipient to enrol).
    environment.systemPackages = [
      pkgs.sops
      pkgs.age
    ];
  };
}
